# vim:fileencoding=utf-8:foldmethod=marker

# Theme: Catppuccin Mocha
include catppuccin-mocha.conf

# Font, run `kitty +list-fonts`
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

# URL styling & handling
url_color #0087bd
url_style curly
open_url_with default

# Copy
copy_on_select yes

# Window
window_alert_on_bell no

# Ternminal Background
background_opacity 0.8
background_blur 40

# Mouse
mouse_hide_wait -3.0

#  Starting shell
#  Default: shell .
shell nu

