# vim:fileencoding=utf-8:foldmethod=marker

# Theme: Catppuccin Mocha
include catppuccin-mocha.conf

# Font, run `kitty +list-fonts`
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0

# URL styling & handling
url_color #0087bd
url_style curly
open_url_with default

# Copy
copy_on_select yes

# Window
window_alert_on_bell no

# Enable when using tiling window manager like i3 or hyprland
# hide_window_decorations yes

# Ternminal Background
background_opacity 0.8
background_blur 40

# Tabs
tab_bar_style powerline
tab_powerline_style round

# Mouse
mouse_hide_wait -3.0

# Split layout will allow new window 
# creation at top right and bottom right
enabled_layouts splits

# Key bindings
map super+d launch --location=vsplit
map super+shift+d launch --location=hsplit

map super+left neighboring_window left
map super+right neighboring_window right
map super+up neighboring_window up
map super+down neighboring_window down

map super+shift+left resize_window narrower
map super+shift+right resize_window wider
map super+shift+up resize_window taller
map super+shift+down resize_window shorter 3
# reset all windows in the tab to the default sizes
map super+shift+home resize_window reset

map super+ctrl+left move_window left
map super+ctrl+right move_window right
map super+ctrl+up move_window up
map super+ctrl+down move_window down

#  Starting shell
#  User default: shell .
shell nu

