name: Dotfiles CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v4
      with:
        submodules: recursive
        token: ${{ secrets.GITHUB_TOKEN }}

  #  - name: "Checkout submodules"
  #    run: |
  #      sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  #      git submodule update --init --recursive

    - name: "Configuration"
      run: echo "DOTFILES_HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: "Update package repository"
      run: sudo apt update

    - name: Install package dependencies
      run: sudo apt-get install -qq bats bc dnsutils

    - name: "Run test"
      run: make test
